version: '3'
services:
  db:
    image: 'postgres:11.1'
    environment:
      POSTGRES_PASSWORD: mgDSt1RY
      POSTGRES_USER: db_user
      POSTGRES_DB: teamopp
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:5432'
    restart: always
  web:
    image: wapplerio/php-7.3-apache
    depends_on:
      - db
    volumes:
      - '../../../:/var/www/html/'
    ports:
      - '8100:80'
    restart: always
    stdin_open: true
    tty: true
